import { ArrowRight } from 'lucide-react'

const communityUrl = 'https://www.skool.com/ainsteinskool-9587/about'

function CommunityButton({ children, className = '' }: { children: React.ReactNode, className?: string }) {
  return <a className={'button button--primary ' + className} href={communityUrl} target="_blank" rel="noreferrer">{children}<ArrowRight size={15} /></a>
}

export default function Home() {
  return <main>
    <div className="ambient ambient--top" /><div className="ambient ambient--bottom" /><div className="page-grid" />
    <nav className="nav shell" aria-label="Main navigation"><div className="nav-left"><a href="#top" className="ainstein-logo nav-portrait" aria-label="Ainstein home"><img src="/images/why-ainstein.png" alt="Ainstein hosts" /></a></div><a href="#top" className="word-logo" aria-label="Ainstein home"><img src="/images/ainstein-word-logo-header.png" alt="Ainstein" /></a><CommunityButton>JOIN AINSTEIN</CommunityButton></nav>
    <section className="hero shell" id="top">
      <div className="hero-title-row"><img className="hero-hosts-cutout" src="/images/hero-hosts-cutout.png" alt="Ainstein hosts presenting a live technology show" fetchPriority="high" /><h1>Tech,<br /><em>shown live.</em></h1></div>
      <section className="case-study-strip" aria-label="Podcast and workshops"><a href="https://www.ainsteinskool.com/podcast" className="case-study-link case-study-link--podcast">PODCAST<ArrowRight size={22} aria-hidden="true" /></a><a href="https://www.ainsteinskool.com/casestudy001" className="case-study-link case-study-link--workshop">WORKSHOP<ArrowRight size={22} aria-hidden="true" /></a><img className="podcast-hover-image" src="/images/podcast-hover-host.png" alt="" aria-hidden="true" /><img className="workshop-hover-image" src="/images/workshop-hover-group.png" alt="" aria-hidden="true" /></section>
    </section>
    <section className="programme programme--access shell" aria-labelledby="programme-title">
      <p className="programme-index">WHAT’S AINSTEIN?</p><h2 id="programme-title">Get closer to how great people think and work.</h2><p className="programme-intro">Ainstein brings you closer to people worth learning from.</p>
      <div className="programme-grid"><article className="programme-card programme-card--life"><div className="programme-image"><img src="/images/programme-life.png" alt="Founder working at a laptop" loading="lazy" /><span>IMAGE / 01</span></div><div className="programme-card-copy"><span>01</span><h3>Find the signal.</h3><p>Learn from people genuinely worth paying attention to.</p></div></article><article className="programme-card programme-card--content"><div className="programme-image"><img src="/images/programme-content.webp" alt="Social media apps on a phone" loading="lazy" /><span>IMAGE / 02</span></div><div className="programme-card-copy"><span>02</span><h3>See the work.</h3><p>Watch how they think, decide and make things live.</p></div></article><article className="programme-card programme-card--growth"><div className="programme-image"><img src="/images/programme-growth.png" alt="Founder working across multiple screens" loading="lazy" /><span>IMAGE / 03</span></div><div className="programme-card-copy"><span>03</span><h3>Keep access open.</h3><p>Useful knowledge shouldn’t automatically sit behind a paywall.</p></div></article></div><p className="programme-outro">Take what’s useful and try it yourself.</p>
    </section>
    <section className="founders shell"><div className="section-heading"><h2>Who’s behind <em>Ainstein</em></h2></div><div className="founder-grid"><article className="founder-card"><img src="/images/amos.webp" alt="Amos, Ainstein founder" loading="lazy" /><div><h3>Amos</h3><p>Built one of Southeast Asia’s fastest-growing new media companies.</p></div></article><article className="founder-card"><img src="/images/maeve-speaker.webp" alt="Maeve speaking at an Ainstein event" loading="lazy" /><div><h3>Maeve</h3><p>Generated 500M+ impressions across AI and emerging tech.</p></div></article></div><p className="founders-together">Together, 1,000+ podcast episodes and interviews with founders and executives across tech.</p></section>
    <section className="community shell"><div><h2>Join the community.</h2></div><div className="flag-list" aria-label="Community locations"><span>🇲🇾</span><span>🇸🇬</span><span>🇻🇳</span><span>🇹🇭</span><span>🇮🇳</span><span>🇮🇩</span><span>🇰🇷</span></div><div className="community-gallery"><img src="/images/community/community-1.png" alt="Ainstein community gathering" loading="lazy" /><img src="/images/community/community-2.png" alt="Ainstein community session" loading="lazy" /><img src="/images/community/community-3.png" alt="Ainstein community event" loading="lazy" /><img src="/images/community/community-4.png" alt="Ainstein community members" loading="lazy" /></div><div className="community-action"><CommunityButton>JOIN AINSTEIN</CommunityButton></div></section>
    <footer className="footer shell"><div className="footer-socials"><a className="button" href="https://www.youtube.com/@AinsteinSkools">YOUTUBE<ArrowRight size={13} /></a><a className="button" href="https://www.instagram.com/ainsteinskool/">INSTAGRAM<ArrowRight size={13} /></a><a className="button" href="https://luma.com/ainstein">EVENT CALENDAR<ArrowRight size={13} /></a></div><span>© 2026 Ainstein Community</span><a href="#top">Back to top ↑</a></footer>
  </main>
}
